version: "3.8"

services:
  postgres:
    build:
      context: .
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - REDIS_HOSTS=local:host.docker.internal:6379

volumes:
  postgres_data:
  redis-data:
